run-dist: install run # сборка и запуск приложения

install: # сборка приложения
	./gradlew installDist

run: # запуск приложения
	./build/install/app/bin/app

clean: # очистка сборки
	./gradlew clean
